dans l'analyse de nos données il en ressort des HYPOTHESE/CONCLUSON.

- il semble que les maisons de ma base sont majoritairement situé dans un quartier qui ne borde pas la rivière Charle

- il semble que ma base contient majoritairement les maison plus anciennes entre 45 et 92 ans

- il semble que plus les maisons ont un accès facile aux autoroutes , plus de taxe frontière augmente

- il semble que plus le nombre de pieces de la maison augmente plus sa valeur augmente/ cette variable semble avoir un impact sur ma variable cicle...ecc

  VALIDONS ces hypothese d'un point de vue statistique, sont t'ils STATISTIQUEMENT SIGNIFICATIVE?

In [93]:
import pandas as pd

In [148]:
df = pd.read_csv("data/boston.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [150]:
df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS         int64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [152]:
df.CHAS = df.CHAS.astype("category")

In [154]:
df.dtypes

CRIM        float64
ZN          float64
INDUS       float64
CHAS       category
NOX         float64
RM          float64
AGE         float64
DIS         float64
RAD           int64
TAX         float64
PTRATIO     float64
B           float64
LSTAT       float64
MEDV        float64
dtype: object

# quanti-quanti

#### confirmation hypothese/ intuition de l'analyse de relation de toutes les variables entre elles compris avec ma variable cicle

##  correlation de pearson

In [103]:
variable_quanti = df.select_dtypes(include = "number").columns.tolist()
variable_quanti

['CRIM',
 'ZN',
 'INDUS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT',
 'MEDV']

In [105]:
df[variable_quanti]

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [107]:
corr_matrix = df[variable_quanti].corr()
corr_matrix

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
CRIM,1.000000,-0.200469,0.406583,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
ZN,-0.200469,1.000000,-0.533828,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
INDUS,0.406583,-0.533828,1.000000,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
NOX,0.420972,-0.516604,0.763651,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
RM,-0.219247,0.311991,-0.391676,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
AGE,0.352734,-0.569537,0.644779,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
DIS,-0.379670,0.664408,-0.708027,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
RAD,0.625505,-0.311948,0.595129,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
TAX,0.582764,-0.314563,0.720760,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
PTRATIO,0.289946,-0.391679,0.383248,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
B,-0.385064,0.175520,-0.356977,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
LSTAT,0.455621,-0.412995,0.603800,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
MEDV,-0.388305,0.360445,-0.483725,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [47]:
from scipy import stats

In [109]:
# creere mon dataframe vide pour stoquer les p_values
p_values_matrix = pd.DataFrame(index = variable_quanti, columns = variable_quanti)

# calculer la correlation et la p_value pour cahque paire de variable
# avec la fonction .loc j'accede a une cellule specitique a parti du nom des ligne et de colonne dans le dataframe p_values_matrix que je viens de creer
# cellule = correspond a l'entersection de var1 et var2 que je rempli avec la p_value correspondant

for var1 in variable_quanti:
    for var2 in variable_quanti:
        if var1 != var2:
            statistic, p_value = stats.pearsonr(df[var1], df[var2])
            p_values_matrix.loc[var1, var2] = p_value
        else:
            # la correlation d'une variable avec elle meme est toujours 1 donc pas besoin de la pevaleur
            p_values_matrix.loc[var1, var2] = 1

# afficher ma matrice de p_value
p_values_matrix

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
CRIM,1,0.000006,0.0,0.0,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZN,0.000006,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000072,0.0,0.0
INDUS,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NOX,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.000019,0.0,0.0,0.0
RM,0.000001,0.0,0.0,0.0,1,0.0,0.000003,0.000002,0.0,0.0,0.003907,0.0,0.0
AGE,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DIS,0.0,0.0,0.0,0.0,0.000003,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0
RAD,0.0,0.0,0.0,0.0,0.000002,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0
TAX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0
PTRATIO,0.0,0.0,0.0,0.000019,0.0,0.0,0.0,0.0,0.0,1,0.00006,0.0,0.0
B,0.0,0.000072,0.0,0.0,0.003907,0.0,0.0,0.0,0.0,0.00006,1,0.0,0.0
LSTAT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0
MEDV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

CONCLUSION
 effectivement il y'a une une correlation lineaire positive entre le nombre de pièce par logement(RM) et la valeur de la maison(MEDV), et la relation est forte
 donc la variable RM a un impact sur ma variable cible et grace a sa p_value < 0,05, cette hypothese est STATISTISTIQUEMENT SIGNIFICATIVE
 
 

- effectivement il y'a  une une correlation lineaire negative entre le pourcentage de la population de statut economique inferieur(LSTAT) et la valeur de la maison(MEDV) et la relation est forte
 donc plus le pourcentage de la population de statut economique inferieur augmente plus le prix de la maison diminue 
  
  et grace sa p_value < 0,05, cette hypothese est STATISTISTIQUEMENT SIGNIFICATIVE




on peut dire que  juste ces 2 variables RM et LSTAT  ont un impact sur ma variable cible, via une realation forte avec celle-ci



-on constate egalement une correlation lineaire positive très forte entre les variables RAD et TAX
et cette relation est statistiquement significative
donc plus les maisons ont un accès facile a l'autoroute, plus la taxe frontière augmente, grace a la p_value cette hypothese est STATISTIQUEMENT SIGNIFICATIVE

donc ont a la 2 variables qui fournissent la meme information , vu qu'il sont fortement correlées( du coup tous les 2 ne seront pas forcement utilisées dans mon modèle)

## test de normalité

In [111]:
# de notre analyque numerique et graphique univarié on a vu que nos variables semblent ne pas etre normalement distribuées
# verifians cela via le test

# test de shapiro-wilk

shapiro_results = {}
for i in variable_quanti:
    shapiro_test = stats.shapiro(df[i])
    shapiro_results[i] = shapiro_test

for key, value in shapiro_results.items():
    print (f"Variable : {key},    Test de shapiro : {value}")

Variable : CRIM,    Test de shapiro : ShapiroResult(statistic=0.44996488094329834, pvalue=1.3285678005931464e-36)
Variable : ZN,    Test de shapiro : ShapiroResult(statistic=0.5559463500976562, pvalue=7.882576753156324e-34)
Variable : INDUS,    Test de shapiro : ShapiroResult(statistic=0.8997918367385864, pvalue=1.0642375893751083e-17)
Variable : NOX,    Test de shapiro : ShapiroResult(statistic=0.9356358051300049, pvalue=5.775851259944009e-14)
Variable : RM,    Test de shapiro : ShapiroResult(statistic=0.9608709812164307, pvalue=2.4107271734408187e-10)
Variable : AGE,    Test de shapiro : ShapiroResult(statistic=0.89201420545578, pvalue=2.2311304847966706e-18)
Variable : DIS,    Test de shapiro : ShapiroResult(statistic=0.9032330513000488, pvalue=2.1851281171594835e-17)
Variable : RAD,    Test de shapiro : ShapiroResult(statistic=0.679641842842102, pvalue=8.072354053650428e-30)
Variable : TAX,    Test de shapiro : ShapiroResult(statistic=0.8152396082878113, pvalue=1.1629790572690724e-23)
Variable : PTRATIO,    Test de shapiro : ShapiroResult(statistic=0.9035943746566772, pvalue=2.359104548622454e-17)
Variable : B,    Test de shapiro : ShapiroResult(statistic=0.47682422399520874, pvalue=6.057845995608311e-36)
Variable : LSTAT,    Test de shapiro : ShapiroResult(statistic=0.9369055032730103, pvalue=8.285112504911873e-14)
Variable : MEDV,    Test de shapiro : ShapiroResult(statistic=0.9171746969223022, pvalue=4.939965499209636e-16)

COCLUSION:

avec les p_value de mes variables très inferieur a 0,05, l'ypothese d'ANORMALITE de mes variables est STATISTIQUMENT SIGNIFICATIVE
donc aucune de mes variables ne suit une distribution normale

# quali-quanti

#### confirmation hypothese/ intuition de l'analyse de relation de toutes les variables quanti et quali entre elles compris avec ma variable cible

notre modalité a 2 variables , on a donc le test de t_student

## entre ma variable cible (MEDV) et ma variable quali(CHAS)

## test de t_student(test parametrique )

### c'est un test parametrique qui repose sur la normalité et l'egalité des variance

le test de t student compare les moyennes de 2 groupes il suppose que les variances sont egales

In [113]:
valeur_maison_rivière = df[df.CHAS == 1]["MEDV"]
valeur_maison_pas_rivière = df[df.CHAS == 0]["MEDV"]
stats.ttest_ind(valeur_maison_rivière, valeur_maison_pas_rivière)

TtestResult(statistic=3.996437466090509, pvalue=7.390623170519905e-05, df=504.0)

conclusion: p_value < 0,05 donc la H0 rejeté la moyenne dans les deux groupes est differente

effectivement sur le graphique selon notre analyse bivarié on voit que les maison qui sont dans un quartier qui borde la rivière ont majoritairement un valeur superieur para rapport au maisons dans un quartier qui ne borde pas la riviere
et grace alla p_value cette difference est STATISTIQUEMENT SIGNIFICATIVE

Donc la proximité a la rivière (CHAS) est une variable qui impact la valeur de la maison ( variable cible)

In [ ]:
# ce test repose sur la normalité et l'egalité des variances / verifions la normalité des sous-groupes

In [115]:
stats.shapiro(valeur_maison_rivière)

ShapiroResult(statistic=0.8359234929084778, pvalue=0.00011230999371036887)

p_value < 0,05 donc l'ypothese de H0 est rejeté, les données ne suivent pas une distribution Normale

In [117]:
stats.shapiro(valeur_maison_pas_rivière)

ShapiroResult(statistic=0.9282609224319458, pvalue=3.1142707905768355e-14)

p_value < 0,05 donc l'ypothese de H0 est rejeté, les donnees ne suivent pas une distribution Normale

In [170]:
# verifions aussi l'egalité des variances entre les 2 groupes
# on a le choix entre  test de levene ou le test de fligner-killer ( tous les 2 sont des test non parametrique qui ne reposent pas sur la normalité) 
#donc trèes adapté dans notre cas

stats.levene(valeur_maison_rivière, valeur_maison_pas_rivière)

# a cote de sa on a le test de barlett( qui par contre repose sur la normalité)

LeveneResult(statistic=4.590342218715871, pvalue=0.03263097600633006)

p_value < 0.05 donc l'ypothese nulle H0 = (les variances dans les deux groupes sont identique) est rejeté 


les variances des sous groupes sont differente/ donc aucune conditions n'est verifié ni la normalité, ni l'egalité des variances
donc le test de t-student n'est pas  adapté/ je ne peu me fier a cela

pour cela j'opte pour un test NON PARAMETRIQUE qui ne repose pas sur la normalité

## test de wilcoxon ( test non_ parametrique)

In [125]:
stats.mannwhitneyu(valeur_maison_rivière, valeur_maison_pas_rivière )

MannwhitneyuResult(statistic=10879.5, pvalue=0.0015816705011294974)

conclusion: p_value < 0,05 l'ypothese H0 rejetée , les moyennes dans les 2 groupes sont differentes


Do effectivement c la proximité a la rivière (CHAS) est une variable qui impact la valeur de la mais

o 
cette hypothese est STATISTIQUEMENT SIGNIFICATIVEe)

In [162]:
variable_quali = df.select_dtypes(exclude = "number").columns.tolist()
variable_quali

['CHAS']

## entre ma variable quali (CHAS) et toutes les autre variables

In [168]:


pvalue_matrix = pd.DataFrame(index = variable_quanti, columns = variable_quali )

for var in variable_quanti:
    valeur_maison_rivière = df.loc[df.CHAS ==1, var]
    valeur_maison_pas_rivière = df.loc[df.CHAS ==0, var]
    statistic, pvalue = stats.mannwhitneyu(valeur_maison_rivière, valeur_maison_pas_rivière)
    

    for qual in variable_quali:
        
        pvalue_matrix.loc[var, qual] = pvalue

pvalue_matrix

             CHAS
CRIM      0.35091
ZN       0.346374
INDUS    0.043557
NOX      0.124271
RM       0.186482
AGE      0.127801
DIS      0.071427
RAD      0.581133
TAX      0.317752
PTRATIO  0.002235
B        0.371308
LSTAT    0.255986
MEDV     0.001582

conclusion:

 effectivement on a une forte relation ente les variables PTRATIO et CHAS
 plus la maison se trouve dans un quartier qui borde la rivière , moins il y'a d'elève dans le quartier par rapport au enseignant
grace a la p_value<0,05 cette hypothese STATISTIQUEMENT SIGNIFICATIVE


 effectivement on a une forte relation ente les variables INDUS et CHAS
  plus les maisons se trouve dans un quartier qui borde la rivière charle , plus elles ont une grande proportion de terrain a usage non commerciale dans le quartier.
  grace a la pvalue<0,05 cette hypothese est STATISTIQUEMENT SIGNIFICATIVE

en CONCLUSION:

- la proximité avec la rivière charle(CHAS)
- le nombre de pièce par logement(RM)
- le pourcentage de la population de statut economique inferieur(LSTAT)

sont des variables qui IMPACT ma variables cible(MEDV) etant fortement correlées a celle-ci

puis on a des variables comme:

- PTRATIO et CHAS
- RAD et TAX
- RAD et CRIM
- INDUS et NOX
- NOX et AGE
- INDUS et TAX 
- DIS et ZN
- INDUS et CHAS

qui sont fortement corrélées entre  elles/ donc apportent forcement la meme information